//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCourse.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlineCourse.Domain.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration is canceled.
        /// </summary>
        public static string CANCELED_REGISTRATION {
            get {
                return ResourceManager.GetString("CANCELED_REGISTRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration is concluded.
        /// </summary>
        public static string CONCLUDED_REGISTRATION {
            get {
                return ResourceManager.GetString("CONCLUDED_REGISTRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Id is already exists.
        /// </summary>
        public static string ID_IS_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("ID_IS_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Course.
        /// </summary>
        public static string INVALID_COURSE {
            get {
                return ResourceManager.GetString("INVALID_COURSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email.
        /// </summary>
        public static string INVALID_EMAIL {
            get {
                return ResourceManager.GetString("INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Student Grade.
        /// </summary>
        public static string INVALID_GRADE_STUDENT {
            get {
                return ResourceManager.GetString("INVALID_GRADE_STUDENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Identification Id.
        /// </summary>
        public static string INVALID_IDENTIFICATION_ID {
            get {
                return ResourceManager.GetString("INVALID_IDENTIFICATION_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Name.
        /// </summary>
        public static string INVALID_NAME {
            get {
                return ResourceManager.GetString("INVALID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Registration.
        /// </summary>
        public static string INVALID_REGISTRATION {
            get {
                return ResourceManager.GetString("INVALID_REGISTRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Student.
        /// </summary>
        public static string INVALID_STUDENT {
            get {
                return ResourceManager.GetString("INVALID_STUDENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Target Audience.
        /// </summary>
        public static string INVALID_TARGETAUDIENCE {
            get {
                return ResourceManager.GetString("INVALID_TARGETAUDIENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Value.
        /// </summary>
        public static string INVALID_VALUE {
            get {
                return ResourceManager.GetString("INVALID_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid WorkLoad.
        /// </summary>
        public static string INVALID_WORKLOAD {
            get {
                return ResourceManager.GetString("INVALID_WORKLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name is already exists.
        /// </summary>
        public static string NAME_IS_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("NAME_IS_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Value should not be bigger than the course Value.
        /// </summary>
        public static string REGISTRATION_VALUE_SHOULD_NOT_BE_BIGGER_THAN_COURSE {
            get {
                return ResourceManager.GetString("REGISTRATION_VALUE_SHOULD_NOT_BE_BIGGER_THAN_COURSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Audience of Student is different of Course.
        /// </summary>
        public static string TARGET_AUDIENCE_IS_DIFERENT_STUDENT_COURSE {
            get {
                return ResourceManager.GetString("TARGET_AUDIENCE_IS_DIFERENT_STUDENT_COURSE", resourceCulture);
            }
        }
    }
}
